# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &laptop age1nw5rh8gcg2lzz20znnmrfn5nx62waprnrez8qg2wf9c2f698vaxsu662gp
  - &station age1nw5rh8gcg2lzz20znnmrfn5nx62waprnrez8qg2wf9c2f698vaxsu662gp
  - &vnpc21 age1nw5rh8gcg2lzz20znnmrfn5nx62waprnrez8qg2wf9c2f698vaxsu662gp
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *laptop
          - *vnpc21
          - *station
