#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
~/.config/polybar/launch.sh &
feh --bg-fill /home/none/Pictures/background/mountain.jpg &
picom &
setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape'

EDP_DISPLAY=$(xrandr | grep -E "^eDP[-0-9]+ connected" | cut -d ' ' -f1)
if xrandr | grep "HDMI-0 connected"; then
    bspc monitor HDMI-0 -d I II III IV V VI VII
    bspc monitor "$EDP_DISPLAY" -d VIII IX X
    xrandr --output HDMI-0 --primary   bspc monitor HDMI-0 -d 1 2 3 4 5 6 7
    autorandr docked
else
    # If HDMI-1 is not connected, use default configuration
    bspc monitor "$EDP_DISPLAY" -d I II III IV V VI VII VIII IX X
fi



bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
bspc config border_width        1.5 

bspc config border_width        3 
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

st -c scratchterm &
bspc rule -a scratchterm sticky=on state=floating hidden=on
bspc rule -a io.github.alainm23.planify.quick-add state=floating


