#!/run/current-system/sw/bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
nm-applet &
~/.config/polybar/launch.sh &
feh --bg-fill /home/odin/Pictures/background/mountain.jpg &
picom &
setxkbmap -option ctrl:nocaps &
xcape -e 'Control_L=Escape'

EDP_DISPLAY=$(xrandr | grep -E "^eDP[-0-9]+ connected" | cut -d ' ' -f1)
if xrandr | grep "DP-3.8 connected"; then
#bspc wm -O DP-3.1 DP-3.8 HDMI-0
    bspc monitor %DP-3.8 -d 1 2 3 4 5
    bspc monitor %DP-3.1 -d 6 7
    bspc monitor HDMI-0 -d 8 9 0

        xrandr --output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate left \
           --output DP-3.8 --mode 2560x1440 --pos 1080x0 --primary \
           --output DP-3.1 --mode 2560x1440 --pos 3640x0 \
           --output "$EDP_DISPLAY" --off
      else
    bspc monitor "$EDP_DISPLAY" -d 1 2 3 4 5 6 7 8 9 0
fi



bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
bspc config border_width        1.5

bspc config border_width        2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

st -c scratchterm &
# bspc rule -a scratchterm sticky=on state=floating hidden=on
# bspc rule -a io.github.alainm23.planify.quick-add state=floating
# bspc rule -a Obsidian desktop='^2' follow=off
# bspc rule -a kitty desktop='^3' follow=off
# bspc rule -a Remmina desktop='^5' follow=off
# bspc rule -a virt-manager desktop='^5' follow=off
