{ ... }:
{
  imports = [
    ./tailscale.nix
    ./gaming.nix
    ./work
    ./password.nix
    ./crypt.nix
    ./hardware
    ./fonts.nix
    ./syncthing.nix
    ./polkit.nix
    ./greetd.nix
    ./localsend.nix
    ./general.nix
    ./ollama.nix
    ./styling.nix
    ./hyprland.nix
    ./plasma.nix
    ./virtualization.nix
    ./security.nix
    ./distributed-builds.nix
    ./init-net.nix
    ./hosted-services
    ./secrets.nix
    ./netbird-client.nix
    ./fail2ban.nix
  ];
}
