[pyprland]
plugins = [
 "expose",
 "fetch_client_menu",
 "lost_windows",
 "magnify",
 "scratchpads",
 "shift_monitors",
 "toggle_special",
 "workspaces_follow_focus",
]

# using variables for demonstration purposes (not needed)
[pyprland.variables]
term_classed = "kitty --class"

[scratchpads.term]
animation = "fromTop"
command = "[term_classed] main-dropterm"
class = "main-dropterm"
size = "75% 60%"
max_size = "1920px 100%"


[scratchpads.gpt]
animation = "fromTop"
command = "kitty --class secound-dropterm claude -m"
class = "secound-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
lazy = true

[scratchpads.notes]
command = "obsidian --disable-gpu"
class = "obsidian"
animation = "fromTop"
size = "75% 60%"
max_size = "1920px 100%"
lazy = true

[scratchpads.todo]
command = "io.github.alainm23.planify"
class = "io.github.alainm23.planify"
animation = "fromTop"
size = "75% 60%"
max_size = "1920px 100%"
lazy = true

# Quick scratchpad for temporary notes
[scratchpads.scratch]
command = "kitty --class scratch-notes zsh -c '~/.config/nixvim/scripts/scratchpad.sh'"
class = "scratch-notes"
animation = "fromTop"
size = "65% 50%"
max_size = "1920px 100%"
margin = 50
unfocus = "hide"
hysteresis = 0.5
lazy = true

# Daily notes in Main vault
[scratchpads.daily]
command = "kitty --class daily-notes nvim ~/Documents/Main/dailyNotes/$(date +%Y-%m-%d).md"
class = "daily-notes"
animation = "fromTop"
size = "80% 70%"
max_size = "1400px 100%"
lazy = true
margin = 50

# Full Main vault access
[scratchpads.vault]
command = "kitty --class vault-notes nvim ~/Documents/Main"
class = "vault-notes"
size = "85% 80%"
animation = "fromRight"
lazy = true

# Cheatsheet viewer with nsxiv
[scratchpads.cheatsheet]
command = "kitty --class cheatsheet-viewer zsh -c '~/.config/hypr/cheatsheet-viewer.sh'"
class = "cheatsheet-viewer"
animation = "fromTop"
size = "90% 90%"
max_size = "1920px 100%"
lazy = true

# Cheatsheet search with vimiv-qt
[scratchpads.cheatsheet-search]
command = "vimiv ~/Pictures/cheatsheets"
class = "vimiv"
animation = "fromTop"
size = "75% 75%"
lazy = true
